Return an empty OsdText string for akuvox R20k.
rosteleset/SmartYard-Server pull request #67
Opened 2024-05-20 13:48 UTC by Airtau

The akuvox doorphone R20k does not support OSD line output.

2024-05-20 14:24 UTC, subs1stem commented
> The akuvox doorphone R20k does not support OSD line output.

Are u sure about this? Maybe this parameter has a different name/path?
Please check the config file or attach the config file here. I think u can download it from the device, to do this go to Update -> Advanced -> Export Autop Template on the device web

2024-06-17 12:23 UTC, Airtau commented
Hi. Yes, I'm sure. There is no OSD option on the RTSP page. In the parameter configuration file too.
![2024-06-17_15-16-00](https://github.com/rosteleset/SmartYard-Server/assets/373510/27ce5d2b-571c-4597-a507-08a9385c829f)
[R20k_Setting.zip](https://github.com/user-attachments/files/15868412/R20k_Setting.zip)

2024-06-21 14:32 UTC, subs1stem requested changes

2024-06-21 14:32 UTC, subs1stem commented on server/hw/ip/camera/akuvox/akuvox.php
> -        return $this->getConfigParams(['Config.DoorSetting.RTSP.OSDText'])[0];
```PHP
return $this->getConfigParams(['Config.DoorSetting.RTSP.OSDText'])[0] ?? '';
```

2024-07-04 13:28 UTC, merged