Update 12.event.md
rosteleset/SmartYard-Server pull request #74
Opened 2024-06-27 12:09 UTC by temandroid

2024-06-27 12:55 UTC, subs1stem requested changes

2024-06-27 12:55 UTC, subs1stem commented on install/12.event.md
> +   systemctl enable event_* --now
When I try to execute this I get:
```bash
Glob pattern passed to enable, but globs are not supported for this.
Invalid unit name "event_*" escaped as "event_\x2a".
Failed to enable unit: Unit file event_\x2a.service does not exist.
```
and without ```--now``` too.

So we have a bug here and I suggest something like this:
```bash
systemctl list-unit-files event_*.service --no-legend --no-pager | awk '{print $1}' | xargs -r -I {} systemctl enable --now {}
```

2024-06-29 21:03 UTC, temandroid commented on install/12.event.md
> +   systemctl enable event_* --now
Hmm, yep, at first you need to change the directory
` cd /etc/systemd/system/ && systemctl enable event_* --now`

2024-07-01 08:11 UTC, subs1stem approved these changes

2024-07-01 08:12 UTC, merged